# Generated by Django 3.1.6 on 2021-04-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugs',
            new_name='slug',
        ),
    ]
